sudo: false
language: python
python:
  - "2.7"
# install dependencies
install:
  - "pip install -r requirements.txt"
# run tests
script: nosetests --exclude optional_tests\|test_nupack
# speed up CI by caching dependencies
cache:
  pip: true
  custom_install: true
